config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'user_exemptions/edit'
    get 'user_exemptions/update'
  end
  namespace :admin do
    get 'quickbooks/index'
  end
  devise_for :admins
  authenticated :admin do
    root 'admin/dashboard#show', as: :authenticated_root
  end

  root to: "products#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :orders, only: [:new, :create, :show]
  resources :invites, only: [:show]

  namespace :cart do
    resources :products, only: [] do
      member do
        post :create
      end
    end
  end

  namespace :admin do
    resources :invites, only: [:index, :create, :new, :edit]
    resource :dashboard, only: [ :show ], controller: 'dashboard'
    resources :products
    resources :liquids, only: [
      :index, :new, :create
    ]
    resources :flavours, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :containers, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :users, only: [:show, :index, :edit, :update]
    resources :user_exemptions, only: [:edit]
    resources :delivery_exemptions, only: [:update]
    resources :orders, only: [:show, :index, :destroy]
    resources :refresh_tokens, only: [:new, :create]
    resources :liquid_prices, only: [:index, :edit, :update, :new, :create]
    get '/quickbooks', to: 'quickbooks#index'
    get '/quickbooks/authorize', to: 'quickbooks#authorize'
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::ApplicationController
  def show
  end
end

app/views/admin/dashboard/show.html.erb
<h1>Admin Dashboard</h1>

<section class="quickbooks-options">
  <h5>Quickbooks</h5>
  <div><%= link_to "Query Quickbooks", admin_quickbooks_authorize_path %></div>
  <div><%= link_to "Refresh Quickbooks Token", new_admin_refresh_token_path %></div>
</section>

<section class="product-options">
  <h5>Products</h5>
  <div>
    <%= link_to "View Products", admin_products_path %>
  </div>
    <%= link_to "View Liquid Prices", admin_liquid_prices_path%>
  <div>

  </div>
  
  <div>
    <%= link_to "View Flavours", admin_flavours_path %>
    |
    <%= link_to "New Flavour", new_admin_flavour_path %>
    </div>

  <div>
    <%= link_to "View Containers", admin_containers_path %>
    |
    <%= link_to "New Container", new_admin_container_path%>
  </div>
  <div>
    <%= link_to "View Liquids", admin_liquids_path %>
    |
    <%= link_to "New Liquid", new_admin_liquid_path %>
  </div>
</section>

<section class="user-options">
  <h5>Accounts</h5>
  <%= link_to "View Users", admin_users_path %>
  |
  <%= link_to "New User", new_admin_invite_path %>
</section>

<section class="order-options">
  <h5>Orders</h5>
  <%= link_to "View Orders", admin_orders_path %>
</section>