config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'user_exemptions/edit'
    get 'user_exemptions/update'
  end
  namespace :admin do
    get 'quickbooks/index'
  end
  devise_for :admins
  authenticated :admin do
    root 'admin/dashboard#show', as: :authenticated_root
  end

  root to: "products#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :orders, only: [:new, :create, :show]
  resources :invites, only: [:show]

  namespace :cart do
    resources :products, only: [] do
      member do
        post :create
      end
    end
  end

  namespace :admin do
    resources :invites, only: [:index, :create, :new, :edit]
    resource :dashboard, only: [ :show ], controller: 'dashboard'
    resources :products
    resources :liquids, only: [
      :index, :new, :create
    ]
    resources :flavours, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :containers, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :users, only: [:show, :index, :edit, :update]
    resources :user_exemptions, only: [:edit]
    resources :delivery_exemptions, only: [:update]
    resources :orders, only: [:show, :index, :destroy]
    resources :refresh_tokens, only: [:new, :create]
    resources :liquid_prices, only: [:index, :edit, :update, :new, :create]
    get '/quickbooks', to: 'quickbooks#index'
    get '/quickbooks/authorize', to: 'quickbooks#authorize'
  end
end

app/models/order.rb
require 'mailgun-ruby'

class Order < ApplicationRecord
  include AASM

  belongs_to :user
  has_many :order_products
  has_many :products, through: :order_products

  attr_reader :created_at

  after_create :email_receipt

  aasm :delivery_status, column: :delivery_status do
    state :undelivered, initial: true
    state :delivered

    event :deliver do
      transitions from: :undelivered, to: :delivered
    end
  end

  VALID_CITIES = [
    'Vancouver',
    'Langley',
    'Surrey',
    'Coquitlam',
    'Port Moody',
    'Maple Ridge',
  ]

  VALID_CITY_CLASSES = %w(
    Vancouver
    Langley
    Surrey
    Coquitlam
    PortMoody
    MapleRidge
  )

  def delivery_date
    make_delivery_date_next_possible(self.shipping_city)
  end

  def make_delivery_date_next_possible(city)
    formatted_city = city.gsub(/ /, '')
    if VALID_CITY_CLASSES.include? formatted_city
      constant = "Delivery::#{formatted_city}"
      city_class = constant.constantize
      return city_class.next_possible_delivery_date.noon
    else
      raise "Missing valid city: #{city} is invalid"
    end
  end

  def subtotal
    total = 0
    order_products.each do |order_product|
      total += (order_product.quantity * order_product.price)
    end
    total += self.delivery_fee
    total += self.environmental_fee
    return total
  end

  def total
    self.taxes + self.subtotal
  end

  def taxes
    0.05 * self.subtotal
  end

  def email
    user.email
  end

  def add_products(cart_products)
    cart_products.each do |cart_product|
      self.order_products << OrderProduct.new(
        order: self,
        product: cart_product.product,
        quantity: cart_product.quantity,
        price: cart_product.product.price_for(self.user),
      )
    end
  end

  def add_user_information(user)
    self.user_id = user.id
    self.shipping_address = user.shipping_address
    self.shipping_city = user.shipping_city
    self.shipping_postal = user.shipping_postal
    self.shipping_province = user.shipping_province
  end

  def delivery_fee
    user.delivery_fee
  end

  def environmental_fee
    total = 0
    order_products.each do |order_product|
      total += order_product.environmental_fee
    end
    return total
  end

  private

  def email_receipt
    # mail(to: "tristanberezowski@gmail.com", subject: "Welcome!").tap do |message|
    #   "Hope this works!"
    # end

    # mg_client = Mailgun::Client.new("f877bd7a-7e120914")

    # message_params =  {
    #                    from: 'tristan@mawji.vc',
    #                    to:   'tristanberezowski@gmail.com',
    #                    subject: 'The Ruby SDK is awesome!',
    #                    text:    'It is really easy to send a message!'
    #                   }
    
    # result = mg_client.send_message('example.com', message_params).to_h!
    
    # message_id = result['id']
    # message = result['message']

    # byebug

  end

  def product_prices
    products.map(&:price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def index
    @orders = Order.all
    @case = Container.find_by(volume: 12 * 375)
    @flavours = Flavour.all
    @undelivered_orders = Order.undelivered
  end

  def show
    @order = Order.find(params[:id])
  end

  def destroy
    @order = Order.find(params[:id])
    @order.order_products.destroy_all
    if @order.destroy
      redirect_to admin_orders_path, notice: t('orders.destroy.success')
    else
      render :index
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @cart = current_user.cart
    @order = Order.new
    @order.user = current_user
  end

  def create
    @order = Order.new(order_params)
    @order.add_user_information(current_user)
    @order.user = current_user
    @order.add_products(cart_products)
    if @order.save
      clear_cart
      redirect_to @order, notice: t('orders.create.success')
    else
      render :new
    end
  end

  def show
    @order = Order.find(params[:id])
  end

  def order_params
    params.require(:order).permit(
      :shipping_address,
      :shipping_city,
      :shipping_postal,
      :shipping_province,
      :shipping_country,
      :note
    )

  end

  def cart_products
    current_user.cart.cart_products
  end

  def clear_cart
    cart_products.destroy_all
  end
end

app/views/admin/orders/index.html.erb
<section class="admin-orders-index">

  <h1>Order Summary</h1>
  <% if @undelivered_orders.first == nil %>
    <h3> No Active Orders </h3>
  <% else %>

    <table class="order-summary-table">
      <thead>
        <th>Name</th>
        <th>Volume Total: (L) / Kegs</th>
        <th>Cases</th>
      </thead>
      <tbody>
        <% @flavours.each do |flavour| %>
          <% if flavour.total_volume_needed(@undelivered_orders) > 0 %>
            <tr>
              <td> <%= flavour.name %></td>
              <td> <%= flavour.total_volume_needed(@undelivered_orders) / 1000 %>
                <%= " / " %> <%= (flavour.total_volume_needed(@undelivered_orders) / 19500.00).round(2) %></td>
              <td> <%= flavour.container_count_needed(@undelivered_orders, @case) %> </td>
            </tr>
            <% end %>
        <% end %>
      </tbody>
    </table>

    <h1>Active/Undelivered Orders</h1>
      <% @undelivered_orders.each do |order| %>
        <section class="order-details">
          <p>Name: <%= order.user.name %></p>
          <p>Name: <%= order.user.company_name %></p>
          <p>Created at: <%= order.created_at %></p>
          <p>Delivery Date: <%= order.delivery_date %></p>
          <% order.order_products.each do |product| %>
            <p><%= product.name %></p>
          <% end %>
          <a class="show-order" href="/admin/orders/<%= order.id %>">View order</a>
        </section>
    <% end %>
  <% end %>

<h1>All Orders</h1>

  <% @orders.each do |order| %>
    <section class="order-details">
      <p>Name: <%= order.user.name %></p>
      <p>Name: <%= order.user.company_name %></p>
      <p>Created at: <%= order.created_at %></p>
      <p>Delivery Date: <%= order.delivery_date %></p>
      <% order.order_products.each do |product| %>
        <p><%= product.name %></p>
      <% end %>
      <a class="show-order" href="/admin/orders/<%= order.id %>">View order</a>
    </section>
  <% end %>
</section>

app/views/admin/orders/show.html.erb
<section class="admin-orders-show">
  <h1>View Order</h1>
  <h4 class="created-at">Created at: <%= @order.created_at%></h4>
  
  <section class="order-details">
    <h2>Order Details</h2>

    <p>Email: <%= @order.email %></p>

    <div class="shipping-information">
      <h4>Shipping Information</h4>
      <p>Name: <%= @order.user.name %></p>
      <p>Name: <%= @order.user.company_name %></p>
      <p>Address: <%= @order.shipping_address %>, <%= @order.shipping_city %></p>
      <p>Postal Code: <%= @order.shipping_postal %></p>
      <p>Created At: <%= @order.created_at %>
    </div>

    <p>Notes: <%= @order.note %></p>

</section>

  <table class="products-table">
    <thead>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
    </thead>

    <tbody>
      <% @order.order_products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.quantity %></td>
          <td><%= humanized_money_with_symbol (product.price * product.quantity) %></td>
        </tr>
      <% end %>
        <tr>
          <td> Delivery Fee </td>
          <td> n/a </td>
          <td> <%= humanized_money_with_symbol @order.delivery_fee %> </td>
        </tr>
        <tr>
          <td> Environmental Fee </td>
          <td> n/a </td>
          <td> <%= humanized_money_with_symbol @order.environmental_fee %> </td>
        <tr>
        <tr><td></td><td></td><td></td></tr>
    </tbody>

    <tfoot>
      <tr>
        <td>Sub-Total</td>
        <td></td>
        <td><%= humanized_money_with_symbol @order.subtotal %></td>
      </tr>
      <tr>
        <td>Taxes</td>
        <td></td>
        <td><%= humanized_money_with_symbol @order.taxes %></td>
      </tr>
      <tr>
        <td>Total</td>
        <td></td>
        <td><%= humanized_money_with_symbol @order.total %></td>
      </tr>
    </tfoot>
  </table>

</section>
  <%= link_to 'Delete this order permanently', admin_order_path(@order), method: :delete, data: { confirm: "Are you sure?" } %>