config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'user_exemptions/edit'
    get 'user_exemptions/update'
  end
  namespace :admin do
    get 'quickbooks/index'
  end
  devise_for :admins
  authenticated :admin do
    root 'admin/dashboard#show', as: :authenticated_root
  end

  root to: "products#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :orders, only: [:new, :create, :show]
  resources :invites, only: [:show]

  namespace :cart do
    resources :products, only: [] do
      member do
        post :create
      end
    end
  end

  namespace :admin do
    resources :invites, only: [:index, :create, :new, :edit]
    resource :dashboard, only: [ :show ], controller: 'dashboard'
    resources :products
    resources :liquids, only: [
      :index, :new, :create
    ]
    resources :flavours, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :containers, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :users, only: [:show, :index, :edit, :update]
    resources :user_exemptions, only: [:edit]
    resources :delivery_exemptions, only: [:update]
    resources :orders, only: [:show, :index, :destroy]
    resources :refresh_tokens, only: [:new, :create]
    resources :liquid_prices, only: [:index, :edit, :update, :new, :create]
    get '/quickbooks', to: 'quickbooks#index'
    get '/quickbooks/authorize', to: 'quickbooks#authorize'
  end
end

app/views/shared/_admin_links.html.erb
<%= link_to 'Home', root_path %>
<div> Logged in as <strong>Admin</strong></div>
<%= link_to(
  "Logout", 
  destroy_admin_session_path, 
  method: :delete,
  :class => 'navbar-link'
) %>

app/views/shared/_navigation.html.erb
<section class="navigation">
  <section class="navigation-title">
    <a href="/" class="logo-link-area">
      <div class="logo">  
        <%= show_svg("logo-lg.svg") %>
      </div>
    </a>
  </section>

  <section class="navigation-links">
    <% if admin_signed_in? %>
      <%= render "shared/admin_links" %>
    <% elsif user_signed_in? %>
      <%= render "shared/user_links" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <p> | </p>
      <%= link_to "Staff Login", new_admin_session_path, :class => 'navbar-link'  %>
    <% end %>
  </section>
</section>

app/views/shared/_user_links.html.erb
<%= link_to 'Home', products_path %>
|
<%= link_to 'Cart', cart_path %>
|
<%= link_to(
  'Edit profile',
  edit_user_registration_path,
  :class => 'navbar-link'
) %> 
|
<%= link_to(
  "Logout",
  destroy_user_session_path,
  method: :delete,
  :class => 'navbar-link'
) %>
|

<p>Logged in as: <strong><%= current_user.email %></strong>.</p>