config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'user_exemptions/edit'
    get 'user_exemptions/update'
  end
  namespace :admin do
    get 'quickbooks/index'
  end
  devise_for :admins
  authenticated :admin do
    root 'admin/dashboard#show', as: :authenticated_root
  end

  root to: "products#index"

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :orders, only: [:new, :create, :show]
  resources :invites, only: [:show]

  namespace :cart do
    resources :products, only: [] do
      member do
        post :create
      end
    end
  end

  namespace :admin do
    resources :invites, only: [:index, :create, :new, :edit]
    resource :dashboard, only: [ :show ], controller: 'dashboard'
    resources :products
    resources :liquids, only: [
      :index, :new, :create
    ]
    resources :flavours, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :containers, only: [
      :index, :new, :create, :edit, :update
    ]
    resources :users, only: [:show, :index, :edit, :update]
    resources :user_exemptions, only: [:edit]
    resources :delivery_exemptions, only: [:update]
    resources :orders, only: [:show, :index, :destroy]
    resources :refresh_tokens, only: [:new, :create]
    resources :liquid_prices, only: [:index, :edit, :update, :new, :create]
    get '/quickbooks', to: 'quickbooks#index'
    get '/quickbooks/authorize', to: 'quickbooks#authorize'
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_products
  has_many :products, through: :cart_products


  def subtotal
    total = 0
    cart_products.each do |cart_product|
      total += cart_product.quantity * cart_product.product.price_for(user)
    end
    total += self.delivery_fee
    total += self.environmental_fee
    total
  end

  def total
    self.taxes + self.subtotal
  end

  def taxes
    0.05 * self.subtotal
  end

  def delivery_fee
    user.delivery_fee
  end

  def environmental_fee
    total = 0
    cart_products.each do |cart_product|
      total += cart_product.environmental_fee
    end
    return total
  end

end

app/controllers/cart/products_controller.rb
class Cart::ProductsController < ApplicationController
  before_action :authenticate_user!

  def create
    @product = Product.find(params[:id])

    @cart_product = CartProduct.new(cart_product_params)
    @cart_product.product = @product
    @cart_product.cart = current_user.cart

    if @cart_product.save
      redirect_to products_path, notice: t('cart_products.create.success')
    else
      redirect_to products_path, notice: t('cart_products.create.fail')
    end
  end

  private

  def cart_product_params
    params.require(:cart_product).permit(
      :quantity,
    )
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @cart = current_user.cart
  end
end

app/views/carts/show.html.erb
<section class="cart-show">
  <h1>Your Cart</h1>
  <table class="products-table">
    <thead>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
    </thead>

    <tbody>
      <% @cart.cart_products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.quantity %></td>
          <td><%= humanized_money_with_symbol (product.price * product.quantity) %></td>
        </tr>
      <% end %>
      <tr>
          <td> Delivery Fee </td>
          <td> n/a </td>
          <td> <%= humanized_money_with_symbol @cart.delivery_fee %> </td>
      </tr>
      <tr>
          <td> Environmental Fee </td>
          <td> n/a </td>
          <td> <%= humanized_money_with_symbol @cart.environmental_fee %> </td>
      <tr>
      <tr><td></td><td></td><td></td></tr>
    </tbody>

    <tfoot>
      <tr>
        <td>Sub-Total</td>
        <td></td>
        <td><%= humanized_money_with_symbol @cart.subtotal %></td>
      </tr>
      <tr>
        <td>Taxes</td>
        <td></td>
        <td><%= humanized_money_with_symbol @cart.taxes %></td>
      </tr>
      <tr>
        <td>Total</td>
        <td></td>
        <td><%= humanized_money_with_symbol @cart.total %></td>
      </tr>
    </tfoot>
  </table>
  <%= link_to 'Checkout', new_order_path, class: 'primary-button' %>
  <%= link_to 'Back', :back, class: 'secondary-button' %>
</section>